version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.1
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.0
    - 2.8.1
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
    - 2.5.4
    - 2.5.5
  - dependency-name: pylint-django
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: docutils
    versions:
    - "0.16"
    - "0.17"
  - dependency-name: django-sass-processor
    versions:
    - 0.8.2
    - 1.0.0
  - dependency-name: elasticsearch
    versions:
    - 7.10.1
    - 7.11.0
    - 7.12.0
  - dependency-name: django-hashid-field
    versions:
    - 3.1.3
    - 3.2.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pyflakes
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: inflect
    versions:
    - 5.0.2
    - 5.0.3
    - 5.2.0
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: django-countries
    versions:
    - "7.0"
  - dependency-name: django-debug-toolbar
    versions:
    - "3.2"
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
  - dependency-name: phabricator
    versions:
    - 0.8.0
  - dependency-name: pycryptodomex
    versions:
    - 3.9.9
  - dependency-name: django-rosetta
    versions:
    - 0.9.5
  - dependency-name: bleach
    versions:
    - 3.1.4
  - dependency-name: django-compressor
    versions:
    - "2.4"
  - dependency-name: gunicorn
    versions:
    - 20.0.4
  - dependency-name: python-daemon
    versions:
    - 2.2.4
  - dependency-name: jinja2
    versions:
    - 2.10.1
